(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/PlayButton.svelte":
/*!******************************************!*\
  !*** ./src/components/PlayButton.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* src/components/PlayButton.svelte generated by Svelte v3.4.4 */


const file = "src/components/PlayButton.svelte";

function create_fragment(ctx) {
	var svg, path, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14;

	return {
		c: function create() {
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			path = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			g0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			this.h()
		},

		l: function claim(nodes) {
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "svg", { version: true, id: true, xmlns: true, "xmlns:xlink": true, x: true, y: true, viewBox: true, style: true, "xml:space": true }, true);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);

			path = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "path", { d: true }, true);
			var path_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path);

			path_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g0);

			g0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g1);

			g1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g2);

			g2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g3);

			g3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g4);

			g4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g5);

			g5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g6);

			g6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g7);

			g7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g8);

			g8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g9);

			g9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g10);

			g10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g11);

			g11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g12);

			g12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g13);

			g13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g14);

			g14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path, "d", "M36.068,20.176l-29-20C6.761-0.035,6.363-0.057,6.035,0.114C5.706,0.287,5.5,0.627,5.5,0.999v40\n    c0,0.372,0.206,0.713,0.535,0.886c0.146,0.076,0.306,0.114,0.465,0.114c0.199,0,0.397-0.06,0.568-0.177l29-20\n    c0.271-0.187,0.432-0.494,0.432-0.823S36.338,20.363,36.068,20.176z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path, file, 10, 2, 244);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g0, file, 14, 2, 536);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g1, file, 15, 2, 544);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g2, file, 16, 2, 552);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g3, file, 17, 2, 560);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g4, file, 18, 2, 568);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g5, file, 19, 2, 576);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g6, file, 20, 2, 584);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g7, file, 21, 2, 592);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g8, file, 22, 2, 600);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g9, file, 23, 2, 608);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g10, file, 24, 2, 616);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g11, file, 25, 2, 624);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g12, file, 26, 2, 632);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g13, file, 27, 2, 640);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g14, file, 28, 2, 648);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "id", "Capa_1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "xmlns:xlink", "http://www.w3.org/1999/xlink");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "x", "0px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "y", "0px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "viewBox", "0 0 41.999 41.999");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(svg, "enable-background", "new 0 0 41.999 41.999");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "xml:space", "preserve");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, svg, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, path);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g14);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(svg);
			}
		}
	};
}

class PlayButton extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (PlayButton);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_PlayButton_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/PlayButton.svelte */ "./src/components/PlayButton.svelte");
/* src/routes/index.svelte generated by Svelte v3.4.4 */




const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-md8zy-style';
	style.textContent = "*{margin:0;padding:0;font-family:\"Oswald\"}.side-info.svelte-md8zy{position:fixed;left:0;bottom:0;display:flex;flex-direction:column;justify-content:flex-end;grid-area:sideinfo;transform:rotate(270deg) translateY(55vh);transform-origin:left bottom;font-weight:bold;line-height:1;padding-left:4vh}.matches.svelte-md8zy{position:fixed;right:0;top:20vh;list-style:none;width:40vw;font-size:8vh;padding:2rem}.matches.svelte-md8zy>li.svelte-md8zy:first-of-type{border-top:1px solid #111}.matches.svelte-md8zy>li.svelte-md8zy{display:grid;grid-template-columns:3em 1fr 3em;width:100%;justify-content:space-between;border-bottom:1px solid #111}.red.svelte-md8zy,.blue.svelte-md8zy{width:8vh}.red.svelte-md8zy{text-align:end}.VS.svelte-md8zy{text-align:center}.time.svelte-md8zy{font-size:35vh;line-height:1.2}.season.svelte-md8zy{font-size:8vh;transform:scaleX(2.3);transform-origin:left}.week.svelte-md8zy{font-size:4vh;font-weight:initial}main.svelte-md8zy{box-sizing:border-box;padding:1rem;color:#111;background:linear-gradient(to top right, #4262ab, #19d9bb 50%);height:100vh;text-transform:uppercase}.partners.svelte-md8zy{display:flex;flex:1}.partners.svelte-md8zy>.svelte-md8zy,.music.svelte-md8zy>.svelte-md8zy{padding:1rem 1rem}.top.svelte-md8zy{display:flex}.music.svelte-md8zy{white-space:nowrap;overflow-x:hidden}.partners.svelte-md8zy>:first-child{border-right:2px solid #222}.partners.svelte-md8zy ul.svelte-md8zy{list-style:none;display:flex;flex:1;grid-gap:3rem}.music.svelte-md8zy{display:flex;justify-content:flex-end}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIjtcbiAgaW1wb3J0IFBsYXlCdXR0b24gZnJvbSBcIi4uL2NvbXBvbmVudHMvUGxheUJ1dHRvbi5zdmVsdGVcIjtcbiAgbGV0IHNlY29uZHMgPSAxMDtcbiAgbGV0IG1pbnV0ZXMgPSAxMjtcblxuICBvbk1vdW50KCgpID0+IHtcbiAgICBjb25zdCBpbnRlcnZhbCA9IHNldEludGVydmFsKCgpID0+IHtcbiAgICAgIGNvbnNvbGUubG9nKFwiaGlcIik7XG4gICAgICBpZiAoc2Vjb25kcyA9PT0gMCkge1xuICAgICAgICBzZWNvbmRzID0gNjA7XG4gICAgICAgIG1pbnV0ZXMgLT0gMTtcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHNlY29uZHMgLT0gMTtcbiAgICAgIH1cbiAgICB9LCAxMDAwKTtcblxuICAgIHJldHVybiAoKSA9PiBjbGVhckludGVydmFsKGludGVydmFsKTtcbiAgfSk7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICA6Z2xvYmFsKCopIHtcbiAgICBtYXJnaW46IDA7XG4gICAgcGFkZGluZzogMDtcbiAgICBmb250LWZhbWlseTogXCJPc3dhbGRcIjtcbiAgfVxuXG4gIC5zaWRlLWluZm8ge1xuICAgIHBvc2l0aW9uOiBmaXhlZDtcbiAgICBsZWZ0OiAwO1xuICAgIGJvdHRvbTogMDtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDtcbiAgICBncmlkLWFyZWE6IHNpZGVpbmZvO1xuICAgIHRyYW5zZm9ybTogcm90YXRlKDI3MGRlZykgdHJhbnNsYXRlWSg1NXZoKTtcbiAgICB0cmFuc2Zvcm0tb3JpZ2luOiBsZWZ0IGJvdHRvbTtcbiAgICBmb250LXdlaWdodDogYm9sZDtcbiAgICBsaW5lLWhlaWdodDogMTtcbiAgICBwYWRkaW5nLWxlZnQ6IDR2aDtcbiAgfVxuXG4gIC5tYXRjaGVzIHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7XG4gICAgcmlnaHQ6IDA7XG4gICAgdG9wOiAyMHZoO1xuICAgIGxpc3Qtc3R5bGU6IG5vbmU7XG4gICAgd2lkdGg6IDQwdnc7XG4gICAgZm9udC1zaXplOiA4dmg7XG4gICAgcGFkZGluZzogMnJlbTtcbiAgfVxuXG4gIC5tYXRjaGVzID4gbGk6Zmlyc3Qtb2YtdHlwZSB7XG4gICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkICMxMTE7XG4gIH1cblxuICAubWF0Y2hlcyA+IGxpIHtcbiAgICBkaXNwbGF5OiBncmlkO1xuICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogM2VtIDFmciAzZW07XG4gICAgd2lkdGg6IDEwMCU7XG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICAgIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCAjMTExO1xuICB9XG4gIC5yZWQsXG4gIC5ibHVlIHtcbiAgICB3aWR0aDogOHZoO1xuICB9XG5cbiAgLnJlZCB7XG4gICAgdGV4dC1hbGlnbjogZW5kO1xuICB9XG5cbiAgLlZTIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIH1cblxuICAudGltZSB7XG4gICAgZm9udC1zaXplOiAzNXZoO1xuICAgIGxpbmUtaGVpZ2h0OiAxLjI7XG4gIH1cblxuICAuc2Vhc29uIHtcbiAgICBmb250LXNpemU6IDh2aDtcbiAgICB0cmFuc2Zvcm06IHNjYWxlWCgyLjMpO1xuICAgIHRyYW5zZm9ybS1vcmlnaW46IGxlZnQ7XG4gIH1cbiAgLndlZWsge1xuICAgIGZvbnQtc2l6ZTogNHZoO1xuICAgIGZvbnQtd2VpZ2h0OiBpbml0aWFsO1xuICB9XG5cbiAgbWFpbiB7XG4gICAgYm94LXNpemluZzogYm9yZGVyLWJveDtcbiAgICBwYWRkaW5nOiAxcmVtO1xuICAgIGNvbG9yOiAjMTExO1xuICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh0byB0b3AgcmlnaHQsICM0MjYyYWIsICMxOWQ5YmIgNTAlKTtcbiAgICBoZWlnaHQ6IDEwMHZoO1xuICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7XG4gIH1cblxuICAucGFydG5lcnMge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleDogMTtcbiAgfVxuXG4gIC5wYXJ0bmVycyA+ICosXG4gIC5tdXNpYyA+ICoge1xuICAgIHBhZGRpbmc6IDFyZW0gMXJlbTtcbiAgfVxuXG4gIC50b3Age1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gIH1cblxuICAubXVzaWMge1xuICAgIHdoaXRlLXNwYWNlOiBub3dyYXA7XG4gICAgb3ZlcmZsb3cteDogaGlkZGVuO1xuICB9XG5cbiAgLnBhcnRuZXJzID4gOmZpcnN0LWNoaWxkIHtcbiAgICBib3JkZXItcmlnaHQ6IDJweCBzb2xpZCAjMjIyO1xuICB9XG5cbiAgLnBhcnRuZXJzIHVsIHtcbiAgICBsaXN0LXN0eWxlOiBub25lO1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleDogMTtcbiAgICBncmlkLWdhcDogM3JlbTtcbiAgfVxuXG4gIC5tdXNpYyB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICB9XG48L3N0eWxlPlxuXG48bWFpbj5cbiAgPGRpdiBjbGFzcz1cInRvcFwiPlxuICAgIDxkaXYgY2xhc3M9XCJwYXJ0bmVyc1wiPlxuICAgICAgPGgyPk9mZmljaWFsIFBhcnRuZXJzPC9oMj5cbiAgICAgIDx1bD5cbiAgICAgICAgPGxpPkZvb3RMb2NrZXI8L2xpPlxuICAgICAgICA8bGk+U2hlbGw8L2xpPlxuICAgICAgICA8bGk+TG9naXRlY2g8L2xpPlxuICAgICAgICA8bGk+RFhSYWNlcjwvbGk+XG4gICAgICA8L3VsPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJtdXNpY1wiPlxuICAgICAgPHA+UGVudGFraWxsIC0gVGVhciBvZiB0aGUgR29kZGVzczwvcD5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJzaWRlLWluZm9cIj5cbiAgICA8ZGl2IGNsYXNzPVwidGltZVwiPiB7bWludXRlc306e3NlY29uZHMgPiA5ID8gc2Vjb25kcyA6ICcwJyArIHNlY29uZHN9IDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJzZWFzb25cIj5TdW1tZXIgMTk8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwid2Vla1wiPndlZWsgb25lPC9kaXY+XG4gIDwvZGl2PlxuICA8b2wgY2xhc3M9XCJtYXRjaGVzXCI+XG4gICAgPGxpPlxuICAgICAgPGRpdiBjbGFzcz1cImJsdWVcIj5HMjwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5TUFk8L2Rpdj5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+T0c8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJWU1wiPlZTPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwicmVkXCI+VklUPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlJHRTwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5NU0Y8L2Rpdj5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+XG4gICAgICAgIDxpbWcgc3JjPVwiL2ZuYy5wbmdcIiAvPlxuICAgICAgPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwiVlNcIj5WUzwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cInJlZFwiPlNLPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlMwNDwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5YTDwvZGl2PlxuICAgIDwvbGk+XG4gIDwvb2w+XG48L21haW4+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBc0JVLENBQUMsQUFBRSxDQUFDLEFBQ1YsTUFBTSxDQUFFLENBQUMsQ0FDVCxPQUFPLENBQUUsQ0FBQyxDQUNWLFdBQVcsQ0FBRSxRQUFRLEFBQ3ZCLENBQUMsQUFFRCxVQUFVLGFBQUMsQ0FBQyxBQUNWLFFBQVEsQ0FBRSxLQUFLLENBQ2YsSUFBSSxDQUFFLENBQUMsQ0FDUCxNQUFNLENBQUUsQ0FBQyxDQUNULE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsZUFBZSxDQUFFLFFBQVEsQ0FDekIsU0FBUyxDQUFFLFFBQVEsQ0FDbkIsU0FBUyxDQUFFLE9BQU8sTUFBTSxDQUFDLENBQUMsV0FBVyxJQUFJLENBQUMsQ0FDMUMsZ0JBQWdCLENBQUUsSUFBSSxDQUFDLE1BQU0sQ0FDN0IsV0FBVyxDQUFFLElBQUksQ0FDakIsV0FBVyxDQUFFLENBQUMsQ0FDZCxZQUFZLENBQUUsR0FBRyxBQUNuQixDQUFDLEFBRUQsUUFBUSxhQUFDLENBQUMsQUFDUixRQUFRLENBQUUsS0FBSyxDQUNmLEtBQUssQ0FBRSxDQUFDLENBQ1IsR0FBRyxDQUFFLElBQUksQ0FDVCxVQUFVLENBQUUsSUFBSSxDQUNoQixLQUFLLENBQUUsSUFBSSxDQUNYLFNBQVMsQ0FBRSxHQUFHLENBQ2QsT0FBTyxDQUFFLElBQUksQUFDZixDQUFDLEFBRUQscUJBQVEsQ0FBRyxlQUFFLGNBQWMsQUFBQyxDQUFDLEFBQzNCLFVBQVUsQ0FBRSxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksQUFDNUIsQ0FBQyxBQUVELHFCQUFRLENBQUcsRUFBRSxhQUFDLENBQUMsQUFDYixPQUFPLENBQUUsSUFBSSxDQUNiLHFCQUFxQixDQUFFLEdBQUcsQ0FBQyxHQUFHLENBQUMsR0FBRyxDQUNsQyxLQUFLLENBQUUsSUFBSSxDQUNYLGVBQWUsQ0FBRSxhQUFhLENBQzlCLGFBQWEsQ0FBRSxHQUFHLENBQUMsS0FBSyxDQUFDLElBQUksQUFDL0IsQ0FBQyxBQUNELGlCQUFJLENBQ0osS0FBSyxhQUFDLENBQUMsQUFDTCxLQUFLLENBQUUsR0FBRyxBQUNaLENBQUMsQUFFRCxJQUFJLGFBQUMsQ0FBQyxBQUNKLFVBQVUsQ0FBRSxHQUFHLEFBQ2pCLENBQUMsQUFFRCxHQUFHLGFBQUMsQ0FBQyxBQUNILFVBQVUsQ0FBRSxNQUFNLEFBQ3BCLENBQUMsQUFFRCxLQUFLLGFBQUMsQ0FBQyxBQUNMLFNBQVMsQ0FBRSxJQUFJLENBQ2YsV0FBVyxDQUFFLEdBQUcsQUFDbEIsQ0FBQyxBQUVELE9BQU8sYUFBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLEdBQUcsQ0FDZCxTQUFTLENBQUUsT0FBTyxHQUFHLENBQUMsQ0FDdEIsZ0JBQWdCLENBQUUsSUFBSSxBQUN4QixDQUFDLEFBQ0QsS0FBSyxhQUFDLENBQUMsQUFDTCxTQUFTLENBQUUsR0FBRyxDQUNkLFdBQVcsQ0FBRSxPQUFPLEFBQ3RCLENBQUMsQUFFRCxJQUFJLGFBQUMsQ0FBQyxBQUNKLFVBQVUsQ0FBRSxVQUFVLENBQ3RCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsS0FBSyxDQUFFLElBQUksQ0FDWCxVQUFVLENBQUUsZ0JBQWdCLEVBQUUsQ0FBQyxHQUFHLENBQUMsS0FBSyxDQUFDLENBQUMsT0FBTyxDQUFDLENBQUMsT0FBTyxDQUFDLEdBQUcsQ0FBQyxDQUMvRCxNQUFNLENBQUUsS0FBSyxDQUNiLGNBQWMsQ0FBRSxTQUFTLEFBQzNCLENBQUMsQUFFRCxTQUFTLGFBQUMsQ0FBQyxBQUNULE9BQU8sQ0FBRSxJQUFJLENBQ2IsSUFBSSxDQUFFLENBQUMsQUFDVCxDQUFDLEFBRUQsc0JBQVMsQ0FBRyxhQUFDLENBQ2IsbUJBQU0sQ0FBRyxhQUFFLENBQUMsQUFDVixPQUFPLENBQUUsSUFBSSxDQUFDLElBQUksQUFDcEIsQ0FBQyxBQUVELElBQUksYUFBQyxDQUFDLEFBQ0osT0FBTyxDQUFFLElBQUksQUFDZixDQUFDLEFBRUQsTUFBTSxhQUFDLENBQUMsQUFDTixXQUFXLENBQUUsTUFBTSxDQUNuQixVQUFVLENBQUUsTUFBTSxBQUNwQixDQUFDLEFBRUQsc0JBQVMsQ0FBRyxZQUFZLEFBQUMsQ0FBQyxBQUN4QixZQUFZLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxJQUFJLEFBQzlCLENBQUMsQUFFRCxzQkFBUyxDQUFDLEVBQUUsYUFBQyxDQUFDLEFBQ1osVUFBVSxDQUFFLElBQUksQ0FDaEIsT0FBTyxDQUFFLElBQUksQ0FDYixJQUFJLENBQUUsQ0FBQyxDQUNQLFFBQVEsQ0FBRSxJQUFJLEFBQ2hCLENBQUMsQUFFRCxNQUFNLGFBQUMsQ0FBQyxBQUNOLE9BQU8sQ0FBRSxJQUFJLENBQ2IsZUFBZSxDQUFFLFFBQVEsQUFDM0IsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var main, div2, div0, h2, t0, t1, ul, li0, t2, t3, li1, t4, t5, li2, t6, t7, li3, t8, t9, div1, p, t10, t11, div6, div3, t12, t13, t14_value = ctx.seconds > 9 ? ctx.seconds : '0' + ctx.seconds, t14, t15, div4, t16, t17, div5, t18, t19, ol, li4, div7, t20, t21, div8, t22, t23, div9, t24, t25, li5, div10, t26, t27, div11, t28, t29, div12, t30, t31, li6, div13, t32, t33, div14, t34, t35, div15, t36, t37, li7, div16, img, t38, div17, t39, t40, div18, t41, t42, li8, div19, t43, t44, div20, t45, t46, div21, t47;

	return {
		c: function create() {
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Official Partners");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("FootLocker");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Shell");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Logitech");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("DXRacer");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pentakill - Tear of the Goddess");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.minutes);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t14_value);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Summer 19");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("week one");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ol");
			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("G2");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("SPY");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("OG");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VIT");
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("RGE");
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t36 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("MSF");
			t37 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t38 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t39 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t40 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t41 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("SK");
			t42 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t43 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("S04");
			t44 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t45 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t46 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t47 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("XL");
			this.h()
		},

		l: function claim(nodes) {
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true }, false);
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Official Partners");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div0_nodes, "\n      ");

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li0_nodes, "FootLocker");
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li1_nodes, "Shell");
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);

			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li2_nodes, "Logitech");
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li3_nodes, "DXRacer");
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n    ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "Pentakill - Tear of the Goddess");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(main_nodes, "\n  ");

			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", { class: true }, false);
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, ctx.minutes);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, ":");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, t14_value);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n    ");

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "Summer 19");
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n    ");

			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);

			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div5_nodes, "week one");
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(main_nodes, "\n  ");

			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "OL", { class: true }, false);
			var ol_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ol);

			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li4);

			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "DIV", { class: true }, false);
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);

			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div7_nodes, "G2");
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li4_nodes, "\n      ");

			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "DIV", { class: true }, false);
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);

			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div8_nodes, "VS");
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li4_nodes, "\n      ");

			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "DIV", { class: true }, false);
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);

			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div9_nodes, "SPY");
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li5);

			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "DIV", { class: true }, false);
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);

			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div10_nodes, "OG");
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li5_nodes, "\n      ");

			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "DIV", { class: true }, false);
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);

			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div11_nodes, "VS");
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li5_nodes, "\n      ");

			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "DIV", { class: true }, false);
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);

			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div12_nodes, "VIT");
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li6);

			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li6_nodes, "DIV", { class: true }, false);
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);

			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div13_nodes, "RGE");
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li6_nodes, "\n      ");

			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li6_nodes, "DIV", { class: true }, false);
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);

			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div14_nodes, "VS");
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li6_nodes, "\n      ");

			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li6_nodes, "DIV", { class: true }, false);
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);

			t36 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div15_nodes, "MSF");
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t37 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li7);

			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li7_nodes, "DIV", { class: true }, false);
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "IMG", { src: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t38 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li7_nodes, "\n      ");

			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li7_nodes, "DIV", { class: true }, false);
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);

			t39 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div17_nodes, "VS");
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t40 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li7_nodes, "\n      ");

			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li7_nodes, "DIV", { class: true }, false);
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);

			t41 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div18_nodes, "SK");
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t42 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li8);

			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li8_nodes, "DIV", { class: true }, false);
			var div19_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div19);

			t43 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div19_nodes, "S04");
			div19_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t44 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li8_nodes, "\n      ");

			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li8_nodes, "DIV", { class: true }, false);
			var div20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div20);

			t45 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div20_nodes, "VS");
			div20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t46 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li8_nodes, "\n      ");

			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li8_nodes, "DIV", { class: true }, false);
			var div21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div21);

			t47 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div21_nodes, "XL");
			div21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			ol_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			h2.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 140, 6, 2239);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 142, 8, 2285);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 143, 8, 2313);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 144, 8, 2336);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 145, 8, 2362);
			ul.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 141, 6, 2272);
			div0.className = "partners svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 139, 4, 2210);
			p.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 149, 6, 2432);
			div1.className = "music svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 148, 4, 2406);
			div2.className = "top svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 138, 2, 2188);
			div3.className = "time svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 153, 4, 2521);
			div4.className = "season svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 154, 4, 2601);
			div5.className = "week svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 155, 4, 2641);
			div6.className = "side-info svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 152, 2, 2493);
			div7.className = "blue svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 159, 6, 2721);
			div8.className = "VS svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 160, 6, 2754);
			div9.className = "red svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 161, 6, 2785);
			li4.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li4, file, 158, 4, 2710);
			div10.className = "blue svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 164, 6, 2837);
			div11.className = "VS svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 165, 6, 2870);
			div12.className = "red svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 166, 6, 2901);
			li5.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li5, file, 163, 4, 2826);
			div13.className = "blue svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 169, 6, 2953);
			div14.className = "VS svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 170, 6, 2987);
			div15.className = "red svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 171, 6, 3018);
			li6.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li6, file, 168, 4, 2942);
			img.src = "/fnc.png";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 175, 8, 3097);
			div16.className = "blue svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 174, 6, 3070);
			div17.className = "VS svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 177, 6, 3139);
			div18.className = "red svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 178, 6, 3170);
			li7.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li7, file, 173, 4, 3059);
			div19.className = "blue svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div19, file, 181, 6, 3221);
			div20.className = "VS svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div20, file, 182, 6, 3255);
			div21.className = "red svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div21, file, 183, 6, 3286);
			li8.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li8, file, 180, 4, 3210);
			ol.className = "matches svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ol, file, 157, 2, 2685);
			main.className = "svelte-md8zy";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 137, 0, 2179);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li2, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li3, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, ol);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div7, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div8, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div9, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div10, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div11, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, t29);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div12, t30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div13, t32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, t33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div14, t34);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, t35);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div15, t36);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t37);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div16, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, t38);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div17, t39);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, t40);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, div18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div18, t41);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t42);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, div19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div19, t43);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, t44);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, div20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div20, t45);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, t46);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, div21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div21, t47);
		},

		p: function update(changed, ctx) {
			if (changed.minutes) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t12, ctx.minutes);
			}

			if ((changed.seconds) && t14_value !== (t14_value = ctx.seconds > 9 ? ctx.seconds : '0' + ctx.seconds)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t14, t14_value);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(main);
			}
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	
  let seconds = 10;
  let minutes = 12;

  Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => {
    const interval = setInterval(() => {
      console.log("hi");
      if (seconds === 0) {
        $$invalidate('seconds', seconds = 60);
        $$invalidate('minutes', minutes -= 1);
      } else {
        $$invalidate('seconds', seconds -= 1);
      }
    }, 1000);

    return () => clearInterval(interval);
  });

	return { seconds, minutes };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-md8zy-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29KQXlKa0MsT0FBTyxHQUFHLENBQUMsT0FBRyxPQUFPLEdBQUcsR0FBRyxPQUFHLE9BQU87Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBFQUEvQyxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0RkFBUCxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OEVBQVAsT0FBTzs7OzJEQUFHLE9BQU8sR0FBRyxDQUFDLE9BQUcsT0FBTyxHQUFHLEdBQUcsT0FBRyxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7OztDQXZKWjtFQUN6RCxJQUFJLE9BQU8sR0FBRyxFQUFFLENBQUM7RUFDakIsSUFBSSxPQUFPLEdBQUcsRUFBRSxDQUFDOztFQUVqQixzREFBTyxDQUFDLE1BQU07SUFDWixNQUFNLFFBQVEsR0FBRyxXQUFXLENBQUMsTUFBTTtNQUNqQyxPQUFPLENBQUMsR0FBRyxDQUFDLElBQUksQ0FBQyxDQUFDO01BQ2xCLElBQUksT0FBTyxLQUFLLENBQUMsRUFBRTtnQ0FDakIsT0FBTyxHQUFHLEdBQUUsQ0FBQztnQ0FDYixPQUFPLElBQUksRUFBQyxDQUFDO09BQ2QsTUFBTTtnQ0FDTCxPQUFPLElBQUksRUFBQyxDQUFDO09BQ2Q7S0FDRixFQUFFLElBQUksQ0FBQyxDQUFDOztJQUVULE9BQU8sTUFBTSxhQUFhLENBQUMsUUFBUSxDQUFDLENBQUM7R0FDdEMsQ0FBQyxDQUFDIiwiZmlsZSI6ImI3N2I1NTZjNmQ2ODcyYzg0Y2UzL2luZGV4LmluZGV4LmpzIiwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIjtcbiAgaW1wb3J0IFBsYXlCdXR0b24gZnJvbSBcIi4uL2NvbXBvbmVudHMvUGxheUJ1dHRvbi5zdmVsdGVcIjtcbiAgbGV0IHNlY29uZHMgPSAxMDtcbiAgbGV0IG1pbnV0ZXMgPSAxMjtcblxuICBvbk1vdW50KCgpID0+IHtcbiAgICBjb25zdCBpbnRlcnZhbCA9IHNldEludGVydmFsKCgpID0+IHtcbiAgICAgIGNvbnNvbGUubG9nKFwiaGlcIik7XG4gICAgICBpZiAoc2Vjb25kcyA9PT0gMCkge1xuICAgICAgICBzZWNvbmRzID0gNjA7XG4gICAgICAgIG1pbnV0ZXMgLT0gMTtcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHNlY29uZHMgLT0gMTtcbiAgICAgIH1cbiAgICB9LCAxMDAwKTtcblxuICAgIHJldHVybiAoKSA9PiBjbGVhckludGVydmFsKGludGVydmFsKTtcbiAgfSk7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICA6Z2xvYmFsKCopIHtcbiAgICBtYXJnaW46IDA7XG4gICAgcGFkZGluZzogMDtcbiAgICBmb250LWZhbWlseTogXCJPc3dhbGRcIjtcbiAgfVxuXG4gIC5zaWRlLWluZm8ge1xuICAgIHBvc2l0aW9uOiBmaXhlZDtcbiAgICBsZWZ0OiAwO1xuICAgIGJvdHRvbTogMDtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDtcbiAgICBncmlkLWFyZWE6IHNpZGVpbmZvO1xuICAgIHRyYW5zZm9ybTogcm90YXRlKDI3MGRlZykgdHJhbnNsYXRlWSg1NXZoKTtcbiAgICB0cmFuc2Zvcm0tb3JpZ2luOiBsZWZ0IGJvdHRvbTtcbiAgICBmb250LXdlaWdodDogYm9sZDtcbiAgICBsaW5lLWhlaWdodDogMTtcbiAgICBwYWRkaW5nLWxlZnQ6IDR2aDtcbiAgfVxuXG4gIC5tYXRjaGVzIHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7XG4gICAgcmlnaHQ6IDA7XG4gICAgdG9wOiAyMHZoO1xuICAgIGxpc3Qtc3R5bGU6IG5vbmU7XG4gICAgd2lkdGg6IDQwdnc7XG4gICAgZm9udC1zaXplOiA4dmg7XG4gICAgcGFkZGluZzogMnJlbTtcbiAgfVxuXG4gIC5tYXRjaGVzID4gbGk6Zmlyc3Qtb2YtdHlwZSB7XG4gICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkICMxMTE7XG4gIH1cblxuICAubWF0Y2hlcyA+IGxpIHtcbiAgICBkaXNwbGF5OiBncmlkO1xuICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogM2VtIDFmciAzZW07XG4gICAgd2lkdGg6IDEwMCU7XG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICAgIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCAjMTExO1xuICB9XG4gIC5yZWQsXG4gIC5ibHVlIHtcbiAgICB3aWR0aDogOHZoO1xuICB9XG5cbiAgLnJlZCB7XG4gICAgdGV4dC1hbGlnbjogZW5kO1xuICB9XG5cbiAgLlZTIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIH1cblxuICAudGltZSB7XG4gICAgZm9udC1zaXplOiAzNXZoO1xuICAgIGxpbmUtaGVpZ2h0OiAxLjI7XG4gIH1cblxuICAuc2Vhc29uIHtcbiAgICBmb250LXNpemU6IDh2aDtcbiAgICB0cmFuc2Zvcm06IHNjYWxlWCgyLjMpO1xuICAgIHRyYW5zZm9ybS1vcmlnaW46IGxlZnQ7XG4gIH1cbiAgLndlZWsge1xuICAgIGZvbnQtc2l6ZTogNHZoO1xuICAgIGZvbnQtd2VpZ2h0OiBpbml0aWFsO1xuICB9XG5cbiAgbWFpbiB7XG4gICAgYm94LXNpemluZzogYm9yZGVyLWJveDtcbiAgICBwYWRkaW5nOiAxcmVtO1xuICAgIGNvbG9yOiAjMTExO1xuICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh0byB0b3AgcmlnaHQsICM0MjYyYWIsICMxOWQ5YmIgNTAlKTtcbiAgICBoZWlnaHQ6IDEwMHZoO1xuICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7XG4gIH1cblxuICAucGFydG5lcnMge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleDogMTtcbiAgfVxuXG4gIC5wYXJ0bmVycyA+ICosXG4gIC5tdXNpYyA+ICoge1xuICAgIHBhZGRpbmc6IDFyZW0gMXJlbTtcbiAgfVxuXG4gIC50b3Age1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gIH1cblxuICAubXVzaWMge1xuICAgIHdoaXRlLXNwYWNlOiBub3dyYXA7XG4gICAgb3ZlcmZsb3cteDogaGlkZGVuO1xuICB9XG5cbiAgLnBhcnRuZXJzID4gOmZpcnN0LWNoaWxkIHtcbiAgICBib3JkZXItcmlnaHQ6IDJweCBzb2xpZCAjMjIyO1xuICB9XG5cbiAgLnBhcnRuZXJzIHVsIHtcbiAgICBsaXN0LXN0eWxlOiBub25lO1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleDogMTtcbiAgICBncmlkLWdhcDogM3JlbTtcbiAgfVxuXG4gIC5tdXNpYyB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICB9XG48L3N0eWxlPlxuXG48bWFpbj5cbiAgPGRpdiBjbGFzcz1cInRvcFwiPlxuICAgIDxkaXYgY2xhc3M9XCJwYXJ0bmVyc1wiPlxuICAgICAgPGgyPk9mZmljaWFsIFBhcnRuZXJzPC9oMj5cbiAgICAgIDx1bD5cbiAgICAgICAgPGxpPkZvb3RMb2NrZXI8L2xpPlxuICAgICAgICA8bGk+U2hlbGw8L2xpPlxuICAgICAgICA8bGk+TG9naXRlY2g8L2xpPlxuICAgICAgICA8bGk+RFhSYWNlcjwvbGk+XG4gICAgICA8L3VsPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJtdXNpY1wiPlxuICAgICAgPHA+UGVudGFraWxsIC0gVGVhciBvZiB0aGUgR29kZGVzczwvcD5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJzaWRlLWluZm9cIj5cbiAgICA8ZGl2IGNsYXNzPVwidGltZVwiPiB7bWludXRlc306e3NlY29uZHMgPiA5ID8gc2Vjb25kcyA6ICcwJyArIHNlY29uZHN9IDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJzZWFzb25cIj5TdW1tZXIgMTk8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwid2Vla1wiPndlZWsgb25lPC9kaXY+XG4gIDwvZGl2PlxuICA8b2wgY2xhc3M9XCJtYXRjaGVzXCI+XG4gICAgPGxpPlxuICAgICAgPGRpdiBjbGFzcz1cImJsdWVcIj5HMjwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5TUFk8L2Rpdj5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+T0c8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJWU1wiPlZTPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwicmVkXCI+VklUPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlJHRTwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5NU0Y8L2Rpdj5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+XG4gICAgICAgIDxpbWcgc3JjPVwiL2ZuYy5wbmdcIiAvPlxuICAgICAgPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwiVlNcIj5WUzwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cInJlZFwiPlNLPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlMwNDwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5YTDwvZGl2PlxuICAgIDwvbGk+XG4gIDwvb2w+XG48L21haW4+XG4iXSwic291cmNlUm9vdCI6IiJ9