(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["index"],{

/***/ "./src/components/PlayButton.svelte":
/*!******************************************!*\
  !*** ./src/components/PlayButton.svelte ***!
  \******************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* src/components/PlayButton.svelte generated by Svelte v3.4.4 */


const file = "src/components/PlayButton.svelte";

function create_fragment(ctx) {
	var svg, path, g0, g1, g2, g3, g4, g5, g6, g7, g8, g9, g10, g11, g12, g13, g14;

	return {
		c: function create() {
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("svg");
			path = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("path");
			g0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			g14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["svg_element"])("g");
			this.h()
		},

		l: function claim(nodes) {
			svg = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "svg", { version: true, id: true, xmlns: true, "xmlns:xlink": true, x: true, y: true, viewBox: true, style: true, "xml:space": true }, true);
			var svg_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(svg);

			path = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "path", { d: true }, true);
			var path_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(path);

			path_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g0);

			g0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g1);

			g1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g2);

			g2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g3);

			g3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g4);

			g4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g5);

			g5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g6);

			g6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g7);

			g7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g8);

			g8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g9);

			g9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g10);

			g10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g11);

			g11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g12);

			g12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g13);

			g13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);

			g14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(svg_nodes, "g", {}, true);
			var g14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(g14);

			g14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			svg_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(path, "d", "M36.068,20.176l-29-20C6.761-0.035,6.363-0.057,6.035,0.114C5.706,0.287,5.5,0.627,5.5,0.999v40\n    c0,0.372,0.206,0.713,0.535,0.886c0.146,0.076,0.306,0.114,0.465,0.114c0.199,0,0.397-0.06,0.568-0.177l29-20\n    c0.271-0.187,0.432-0.494,0.432-0.823S36.338,20.363,36.068,20.176z");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(path, file, 10, 2, 244);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g0, file, 14, 2, 536);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g1, file, 15, 2, 544);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g2, file, 16, 2, 552);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g3, file, 17, 2, 560);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g4, file, 18, 2, 568);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g5, file, 19, 2, 576);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g6, file, 20, 2, 584);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g7, file, 21, 2, 592);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g8, file, 22, 2, 600);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g9, file, 23, 2, 608);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g10, file, 24, 2, 616);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g11, file, 25, 2, 624);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g12, file, 26, 2, 632);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g13, file, 27, 2, 640);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(g14, file, 28, 2, 648);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "version", "1.1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "id", "Capa_1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "xmlns", "http://www.w3.org/2000/svg");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "xmlns:xlink", "http://www.w3.org/1999/xlink");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "x", "0px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "y", "0px");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "viewBox", "0 0 41.999 41.999");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_style"])(svg, "enable-background", "new 0 0 41.999 41.999");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr"])(svg, "xml:space", "preserve");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(svg, file, 0, 0, 0);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, svg, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, path);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(svg, g14);
		},

		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(svg);
			}
		}
	};
}

class PlayButton extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, null, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (PlayButton);

/***/ }),

/***/ "./src/routes/index.svelte":
/*!*********************************!*\
  !*** ./src/routes/index.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal.mjs");
/* harmony import */ var svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! svelte */ "./node_modules/svelte/index.mjs");
/* harmony import */ var _components_PlayButton_svelte__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! ../components/PlayButton.svelte */ "./src/components/PlayButton.svelte");
/* src/routes/index.svelte generated by Svelte v3.4.4 */




const file = "src/routes/index.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = 'svelte-1u760zj-style';
	style.textContent = "*{margin:0;padding:0;font-family:\"Oswald\"}.side-info.svelte-1u760zj{position:fixed;left:0;bottom:0;display:flex;flex-direction:column;justify-content:flex-end;grid-area:sideinfo;transform:rotate(270deg) translateY(55vh);transform-origin:left bottom;font-weight:bold;line-height:1;padding-left:4vh}.matches.svelte-1u760zj{position:fixed;right:0;top:20vh;list-style:none;width:40vw;font-size:8vh;padding:2rem}.matches.svelte-1u760zj>li.svelte-1u760zj:first-of-type{border-top:1px solid #111}.matches.svelte-1u760zj>li.svelte-1u760zj{display:grid;grid-template-columns:3em 1fr 3em;width:100%;justify-content:space-between;border-bottom:1px solid #111}.blue.svelte-1u760zj>img.svelte-1u760zj{height:8vh;margin:0 3vh}.red.svelte-1u760zj{text-align:end}.VS.svelte-1u760zj{text-align:center}.time.svelte-1u760zj{font-size:35vh;line-height:1.2}.season.svelte-1u760zj{font-size:8vh;transform:scaleX(2.3);transform-origin:left}.week.svelte-1u760zj{font-size:4vh;font-weight:initial}main.svelte-1u760zj{box-sizing:border-box;padding:1rem;color:#111;background:linear-gradient(to top right, #4262ab, #19d9bb 50%);height:100vh;text-transform:uppercase}.partners.svelte-1u760zj{display:flex;flex:1}.partners.svelte-1u760zj>.svelte-1u760zj,.music.svelte-1u760zj>.svelte-1u760zj{padding:1rem 1rem}.top.svelte-1u760zj{display:flex}.music.svelte-1u760zj{white-space:nowrap;overflow-x:hidden}.partners.svelte-1u760zj>:first-child{border-right:2px solid #222}.partners.svelte-1u760zj ul.svelte-1u760zj{list-style:none;display:flex;flex:1;grid-gap:3rem}.music.svelte-1u760zj{display:flex;justify-content:flex-end}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguc3ZlbHRlIiwic291cmNlcyI6WyJpbmRleC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgaW1wb3J0IHsgb25Nb3VudCB9IGZyb20gXCJzdmVsdGVcIjtcbiAgaW1wb3J0IFBsYXlCdXR0b24gZnJvbSBcIi4uL2NvbXBvbmVudHMvUGxheUJ1dHRvbi5zdmVsdGVcIjtcbiAgbGV0IHNlY29uZHMgPSAxMDtcbiAgbGV0IG1pbnV0ZXMgPSAxMjtcblxuICBvbk1vdW50KCgpID0+IHtcbiAgICBjb25zdCBpbnRlcnZhbCA9IHNldEludGVydmFsKCgpID0+IHtcbiAgICAgIGNvbnNvbGUubG9nKFwiaGlcIik7XG4gICAgICBpZiAoc2Vjb25kcyA9PT0gMCkge1xuICAgICAgICBzZWNvbmRzID0gNjA7XG4gICAgICAgIG1pbnV0ZXMgLT0gMTtcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHNlY29uZHMgLT0gMTtcbiAgICAgIH1cbiAgICB9LCAxMDAwKTtcblxuICAgIHJldHVybiAoKSA9PiBjbGVhckludGVydmFsKGludGVydmFsKTtcbiAgfSk7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICA6Z2xvYmFsKCopIHtcbiAgICBtYXJnaW46IDA7XG4gICAgcGFkZGluZzogMDtcbiAgICBmb250LWZhbWlseTogXCJPc3dhbGRcIjtcbiAgfVxuXG4gIC5zaWRlLWluZm8ge1xuICAgIHBvc2l0aW9uOiBmaXhlZDtcbiAgICBsZWZ0OiAwO1xuICAgIGJvdHRvbTogMDtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47XG4gICAganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDtcbiAgICBncmlkLWFyZWE6IHNpZGVpbmZvO1xuICAgIHRyYW5zZm9ybTogcm90YXRlKDI3MGRlZykgdHJhbnNsYXRlWSg1NXZoKTtcbiAgICB0cmFuc2Zvcm0tb3JpZ2luOiBsZWZ0IGJvdHRvbTtcbiAgICBmb250LXdlaWdodDogYm9sZDtcbiAgICBsaW5lLWhlaWdodDogMTtcbiAgICBwYWRkaW5nLWxlZnQ6IDR2aDtcbiAgfVxuXG4gIC5tYXRjaGVzIHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7XG4gICAgcmlnaHQ6IDA7XG4gICAgdG9wOiAyMHZoO1xuICAgIGxpc3Qtc3R5bGU6IG5vbmU7XG4gICAgd2lkdGg6IDQwdnc7XG4gICAgZm9udC1zaXplOiA4dmg7XG4gICAgcGFkZGluZzogMnJlbTtcbiAgfVxuXG4gIC5tYXRjaGVzID4gbGk6Zmlyc3Qtb2YtdHlwZSB7XG4gICAgYm9yZGVyLXRvcDogMXB4IHNvbGlkICMxMTE7XG4gIH1cblxuICAubWF0Y2hlcyA+IGxpIHtcbiAgICBkaXNwbGF5OiBncmlkO1xuICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogM2VtIDFmciAzZW07XG4gICAgd2lkdGg6IDEwMCU7XG4gICAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xuICAgIGJvcmRlci1ib3R0b206IDFweCBzb2xpZCAjMTExO1xuICB9XG4gIC5yZWQgPiBpbWcsXG4gIC5ibHVlID4gaW1nIHtcbiAgICBoZWlnaHQ6IDh2aDtcbiAgICBtYXJnaW46IDAgM3ZoO1xuICB9XG5cbiAgLnJlZCB7XG4gICAgdGV4dC1hbGlnbjogZW5kO1xuICB9XG5cbiAgLlZTIHtcbiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIH1cblxuICAudGltZSB7XG4gICAgZm9udC1zaXplOiAzNXZoO1xuICAgIGxpbmUtaGVpZ2h0OiAxLjI7XG4gIH1cblxuICAuc2Vhc29uIHtcbiAgICBmb250LXNpemU6IDh2aDtcbiAgICB0cmFuc2Zvcm06IHNjYWxlWCgyLjMpO1xuICAgIHRyYW5zZm9ybS1vcmlnaW46IGxlZnQ7XG4gIH1cbiAgLndlZWsge1xuICAgIGZvbnQtc2l6ZTogNHZoO1xuICAgIGZvbnQtd2VpZ2h0OiBpbml0aWFsO1xuICB9XG5cbiAgbWFpbiB7XG4gICAgYm94LXNpemluZzogYm9yZGVyLWJveDtcbiAgICBwYWRkaW5nOiAxcmVtO1xuICAgIGNvbG9yOiAjMTExO1xuICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh0byB0b3AgcmlnaHQsICM0MjYyYWIsICMxOWQ5YmIgNTAlKTtcbiAgICBoZWlnaHQ6IDEwMHZoO1xuICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7XG4gIH1cblxuICAucGFydG5lcnMge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleDogMTtcbiAgfVxuXG4gIC5wYXJ0bmVycyA+ICosXG4gIC5tdXNpYyA+ICoge1xuICAgIHBhZGRpbmc6IDFyZW0gMXJlbTtcbiAgfVxuXG4gIC50b3Age1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gIH1cblxuICAubXVzaWMge1xuICAgIHdoaXRlLXNwYWNlOiBub3dyYXA7XG4gICAgb3ZlcmZsb3cteDogaGlkZGVuO1xuICB9XG5cbiAgLnBhcnRuZXJzID4gOmZpcnN0LWNoaWxkIHtcbiAgICBib3JkZXItcmlnaHQ6IDJweCBzb2xpZCAjMjIyO1xuICB9XG5cbiAgLnBhcnRuZXJzIHVsIHtcbiAgICBsaXN0LXN0eWxlOiBub25lO1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgZmxleDogMTtcbiAgICBncmlkLWdhcDogM3JlbTtcbiAgfVxuXG4gIC5tdXNpYyB7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xuICB9XG48L3N0eWxlPlxuXG48bWFpbj5cbiAgPGRpdiBjbGFzcz1cInRvcFwiPlxuICAgIDxkaXYgY2xhc3M9XCJwYXJ0bmVyc1wiPlxuICAgICAgPGgyPk9mZmljaWFsIFBhcnRuZXJzPC9oMj5cbiAgICAgIDx1bD5cbiAgICAgICAgPGxpPkZvb3RMb2NrZXI8L2xpPlxuICAgICAgICA8bGk+U2hlbGw8L2xpPlxuICAgICAgICA8bGk+TG9naXRlY2g8L2xpPlxuICAgICAgICA8bGk+RFhSYWNlcjwvbGk+XG4gICAgICA8L3VsPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJtdXNpY1wiPlxuICAgICAgPHA+UGVudGFraWxsIC0gVGVhciBvZiB0aGUgR29kZGVzczwvcD5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJzaWRlLWluZm9cIj5cbiAgICA8ZGl2IGNsYXNzPVwidGltZVwiPiB7bWludXRlc306e3NlY29uZHMgPiA5ID8gc2Vjb25kcyA6ICcwJyArIHNlY29uZHN9IDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJzZWFzb25cIj5TdW1tZXIgMTk8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwid2Vla1wiPndlZWsgb25lPC9kaXY+XG4gIDwvZGl2PlxuICA8b2wgY2xhc3M9XCJtYXRjaGVzXCI+XG4gICAgPGxpPlxuICAgICAgPGRpdiBjbGFzcz1cImJsdWVcIj5HMjwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5TUFk8L2Rpdj5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+T0c8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJWU1wiPlZTPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwicmVkXCI+VklUPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlJHRTwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5NU0Y8L2Rpdj5cbiAgICA8L2xpPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+XG4gICAgICAgIDxpbWcgc3JjPVwiL2ZuYy5wbmdcIiAvPlxuICAgICAgPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwiVlNcIj5WUzwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cInJlZFwiPlNLPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlMwNDwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5YTDwvZGl2PlxuICAgIDwvbGk+XG4gIDwvb2w+XG48L21haW4+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBc0JVLENBQUMsQUFBRSxDQUFDLEFBQ1YsTUFBTSxDQUFFLENBQUMsQ0FDVCxPQUFPLENBQUUsQ0FBQyxDQUNWLFdBQVcsQ0FBRSxRQUFRLEFBQ3ZCLENBQUMsQUFFRCxVQUFVLGVBQUMsQ0FBQyxBQUNWLFFBQVEsQ0FBRSxLQUFLLENBQ2YsSUFBSSxDQUFFLENBQUMsQ0FDUCxNQUFNLENBQUUsQ0FBQyxDQUNULE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLE1BQU0sQ0FDdEIsZUFBZSxDQUFFLFFBQVEsQ0FDekIsU0FBUyxDQUFFLFFBQVEsQ0FDbkIsU0FBUyxDQUFFLE9BQU8sTUFBTSxDQUFDLENBQUMsV0FBVyxJQUFJLENBQUMsQ0FDMUMsZ0JBQWdCLENBQUUsSUFBSSxDQUFDLE1BQU0sQ0FDN0IsV0FBVyxDQUFFLElBQUksQ0FDakIsV0FBVyxDQUFFLENBQUMsQ0FDZCxZQUFZLENBQUUsR0FBRyxBQUNuQixDQUFDLEFBRUQsUUFBUSxlQUFDLENBQUMsQUFDUixRQUFRLENBQUUsS0FBSyxDQUNmLEtBQUssQ0FBRSxDQUFDLENBQ1IsR0FBRyxDQUFFLElBQUksQ0FDVCxVQUFVLENBQUUsSUFBSSxDQUNoQixLQUFLLENBQUUsSUFBSSxDQUNYLFNBQVMsQ0FBRSxHQUFHLENBQ2QsT0FBTyxDQUFFLElBQUksQUFDZixDQUFDLEFBRUQsdUJBQVEsQ0FBRyxpQkFBRSxjQUFjLEFBQUMsQ0FBQyxBQUMzQixVQUFVLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxJQUFJLEFBQzVCLENBQUMsQUFFRCx1QkFBUSxDQUFHLEVBQUUsZUFBQyxDQUFDLEFBQ2IsT0FBTyxDQUFFLElBQUksQ0FDYixxQkFBcUIsQ0FBRSxHQUFHLENBQUMsR0FBRyxDQUFDLEdBQUcsQ0FDbEMsS0FBSyxDQUFFLElBQUksQ0FDWCxlQUFlLENBQUUsYUFBYSxDQUM5QixhQUFhLENBQUUsR0FBRyxDQUFDLEtBQUssQ0FBQyxJQUFJLEFBQy9CLENBQUMsQUFFRCxvQkFBSyxDQUFHLEdBQUcsZUFBQyxDQUFDLEFBQ1gsTUFBTSxDQUFFLEdBQUcsQ0FDWCxNQUFNLENBQUUsQ0FBQyxDQUFDLEdBQUcsQUFDZixDQUFDLEFBRUQsSUFBSSxlQUFDLENBQUMsQUFDSixVQUFVLENBQUUsR0FBRyxBQUNqQixDQUFDLEFBRUQsR0FBRyxlQUFDLENBQUMsQUFDSCxVQUFVLENBQUUsTUFBTSxBQUNwQixDQUFDLEFBRUQsS0FBSyxlQUFDLENBQUMsQUFDTCxTQUFTLENBQUUsSUFBSSxDQUNmLFdBQVcsQ0FBRSxHQUFHLEFBQ2xCLENBQUMsQUFFRCxPQUFPLGVBQUMsQ0FBQyxBQUNQLFNBQVMsQ0FBRSxHQUFHLENBQ2QsU0FBUyxDQUFFLE9BQU8sR0FBRyxDQUFDLENBQ3RCLGdCQUFnQixDQUFFLElBQUksQUFDeEIsQ0FBQyxBQUNELEtBQUssZUFBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLEdBQUcsQ0FDZCxXQUFXLENBQUUsT0FBTyxBQUN0QixDQUFDLEFBRUQsSUFBSSxlQUFDLENBQUMsQUFDSixVQUFVLENBQUUsVUFBVSxDQUN0QixPQUFPLENBQUUsSUFBSSxDQUNiLEtBQUssQ0FBRSxJQUFJLENBQ1gsVUFBVSxDQUFFLGdCQUFnQixFQUFFLENBQUMsR0FBRyxDQUFDLEtBQUssQ0FBQyxDQUFDLE9BQU8sQ0FBQyxDQUFDLE9BQU8sQ0FBQyxHQUFHLENBQUMsQ0FDL0QsTUFBTSxDQUFFLEtBQUssQ0FDYixjQUFjLENBQUUsU0FBUyxBQUMzQixDQUFDLEFBRUQsU0FBUyxlQUFDLENBQUMsQUFDVCxPQUFPLENBQUUsSUFBSSxDQUNiLElBQUksQ0FBRSxDQUFDLEFBQ1QsQ0FBQyxBQUVELHdCQUFTLENBQUcsZUFBQyxDQUNiLHFCQUFNLENBQUcsZUFBRSxDQUFDLEFBQ1YsT0FBTyxDQUFFLElBQUksQ0FBQyxJQUFJLEFBQ3BCLENBQUMsQUFFRCxJQUFJLGVBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxJQUFJLEFBQ2YsQ0FBQyxBQUVELE1BQU0sZUFBQyxDQUFDLEFBQ04sV0FBVyxDQUFFLE1BQU0sQ0FDbkIsVUFBVSxDQUFFLE1BQU0sQUFDcEIsQ0FBQyxBQUVELHdCQUFTLENBQUcsWUFBWSxBQUFDLENBQUMsQUFDeEIsWUFBWSxDQUFFLEdBQUcsQ0FBQyxLQUFLLENBQUMsSUFBSSxBQUM5QixDQUFDLEFBRUQsd0JBQVMsQ0FBQyxFQUFFLGVBQUMsQ0FBQyxBQUNaLFVBQVUsQ0FBRSxJQUFJLENBQ2hCLE9BQU8sQ0FBRSxJQUFJLENBQ2IsSUFBSSxDQUFFLENBQUMsQ0FDUCxRQUFRLENBQUUsSUFBSSxBQUNoQixDQUFDLEFBRUQsTUFBTSxlQUFDLENBQUMsQUFDTixPQUFPLENBQUUsSUFBSSxDQUNiLGVBQWUsQ0FBRSxRQUFRLEFBQzNCLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(document.head, style);
}

function create_fragment(ctx) {
	var main, div2, div0, h2, t0, t1, ul, li0, t2, t3, li1, t4, t5, li2, t6, t7, li3, t8, t9, div1, p, t10, t11, div6, div3, t12, t13, t14_value = ctx.seconds > 9 ? ctx.seconds : '0' + ctx.seconds, t14, t15, div4, t16, t17, div5, t18, t19, ol, li4, div7, t20, t21, div8, t22, t23, div9, t24, t25, li5, div10, t26, t27, div11, t28, t29, div12, t30, t31, li6, div13, t32, t33, div14, t34, t35, div15, t36, t37, li7, div16, img, t38, div17, t39, t40, div18, t41, t42, li8, div19, t43, t44, div20, t45, t46, div21, t47;

	return {
		c: function create() {
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("main");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h2");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Official Partners");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ul");
			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("FootLocker");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Shell");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Logitech");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("DXRacer");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pentakill - Tear of the Goddess");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(ctx.minutes);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(":");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t14_value);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Summer 19");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("week one");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("ol");
			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("G2");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("SPY");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("OG");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VIT");
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("RGE");
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t36 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("MSF");
			t37 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t38 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t39 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t40 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t41 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("SK");
			t42 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			li8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("li");
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t43 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("S04");
			t44 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t45 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("VS");
			t46 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			t47 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("XL");
			this.h()
		},

		l: function claim(nodes) {
			main = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "MAIN", { class: true }, false);
			var main_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(main);

			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", { class: true }, false);
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);

			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);

			h2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H2", { class: true }, false);
			var h2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h2);

			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h2_nodes, "Official Partners");
			h2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div0_nodes, "\n      ");

			ul = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "UL", { class: true }, false);
			var ul_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ul);

			li0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li0);

			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li0_nodes, "FootLocker");
			li0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li1);

			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li1_nodes, "Shell");
			li1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li2);

			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li2_nodes, "Logitech");
			li2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ul_nodes, "\n        ");

			li3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ul_nodes, "LI", {}, false);
			var li3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li3);

			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li3_nodes, "DXRacer");
			li3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			ul_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div2_nodes, "\n    ");

			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true }, false);
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);

			p = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true }, false);
			var p_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p);

			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p_nodes, "Pentakill - Tear of the Goddess");
			p_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(main_nodes, "\n  ");

			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "DIV", { class: true }, false);
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);

			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);

			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, ctx.minutes);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, ":");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div3_nodes, t14_value);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n    ");

			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);

			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div4_nodes, "Summer 19");
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div6_nodes, "\n    ");

			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true }, false);
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);

			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div5_nodes, "week one");
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(main_nodes, "\n  ");

			ol = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(main_nodes, "OL", { class: true }, false);
			var ol_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(ol);

			li4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li4);

			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "DIV", { class: true }, false);
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);

			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div7_nodes, "G2");
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li4_nodes, "\n      ");

			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "DIV", { class: true }, false);
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);

			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div8_nodes, "VS");
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li4_nodes, "\n      ");

			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li4_nodes, "DIV", { class: true }, false);
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);

			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div9_nodes, "SPY");
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li5);

			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "DIV", { class: true }, false);
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);

			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div10_nodes, "OG");
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li5_nodes, "\n      ");

			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "DIV", { class: true }, false);
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);

			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div11_nodes, "VS");
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li5_nodes, "\n      ");

			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li5_nodes, "DIV", { class: true }, false);
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);

			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div12_nodes, "VIT");
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li6);

			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li6_nodes, "DIV", { class: true }, false);
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);

			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div13_nodes, "RGE");
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li6_nodes, "\n      ");

			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li6_nodes, "DIV", { class: true }, false);
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);

			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div14_nodes, "VS");
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t35 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li6_nodes, "\n      ");

			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li6_nodes, "DIV", { class: true }, false);
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);

			t36 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div15_nodes, "MSF");
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t37 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li7);

			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li7_nodes, "DIV", { class: true }, false);
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);

			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "IMG", { src: true, class: true }, false);
			var img_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(img);

			img_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t38 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li7_nodes, "\n      ");

			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li7_nodes, "DIV", { class: true }, false);
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);

			t39 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div17_nodes, "VS");
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t40 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li7_nodes, "\n      ");

			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li7_nodes, "DIV", { class: true }, false);
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);

			t41 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div18_nodes, "SK");
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t42 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(ol_nodes, "\n    ");

			li8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(ol_nodes, "LI", { class: true }, false);
			var li8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(li8);

			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li8_nodes, "DIV", { class: true }, false);
			var div19_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div19);

			t43 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div19_nodes, "S04");
			div19_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t44 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li8_nodes, "\n      ");

			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li8_nodes, "DIV", { class: true }, false);
			var div20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div20);

			t45 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div20_nodes, "VS");
			div20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			t46 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(li8_nodes, "\n      ");

			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(li8_nodes, "DIV", { class: true }, false);
			var div21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div21);

			t47 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(div21_nodes, "XL");
			div21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			li8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			ol_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			main_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"]);
			this.h();
		},

		h: function hydrate() {
			h2.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h2, file, 141, 6, 2271);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li0, file, 143, 8, 2317);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li1, file, 144, 8, 2345);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li2, file, 145, 8, 2368);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li3, file, 146, 8, 2394);
			ul.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ul, file, 142, 6, 2304);
			div0.className = "partners svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 140, 4, 2242);
			p.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p, file, 150, 6, 2464);
			div1.className = "music svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 149, 4, 2438);
			div2.className = "top svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 139, 2, 2220);
			div3.className = "time svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 154, 4, 2553);
			div4.className = "season svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 155, 4, 2633);
			div5.className = "week svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 156, 4, 2673);
			div6.className = "side-info svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 153, 2, 2525);
			div7.className = "blue";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 160, 6, 2753);
			div8.className = "VS svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 161, 6, 2786);
			div9.className = "red svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 162, 6, 2817);
			li4.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li4, file, 159, 4, 2742);
			div10.className = "blue";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 165, 6, 2869);
			div11.className = "VS svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 166, 6, 2902);
			div12.className = "red svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 167, 6, 2933);
			li5.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li5, file, 164, 4, 2858);
			div13.className = "blue";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 170, 6, 2985);
			div14.className = "VS svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 171, 6, 3019);
			div15.className = "red svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 172, 6, 3050);
			li6.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li6, file, 169, 4, 2974);
			img.src = "/fnc.png";
			img.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 176, 8, 3129);
			div16.className = "blue svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 175, 6, 3102);
			div17.className = "VS svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 178, 6, 3171);
			div18.className = "red svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 179, 6, 3202);
			li7.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li7, file, 174, 4, 3091);
			div19.className = "blue";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div19, file, 182, 6, 3253);
			div20.className = "VS svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div20, file, 183, 6, 3287);
			div21.className = "red svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div21, file, 184, 6, 3318);
			li8.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(li8, file, 181, 4, 3242);
			ol.className = "matches svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(ol, file, 158, 2, 2717);
			main.className = "svelte-1u760zj";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(main, file, 138, 0, 2211);
		},

		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert"])(target, main, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, h2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(h2, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div0, ul);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li0, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li1, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li2, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ul, li3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li3, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div1, p);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(p, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div3, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div4, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div5, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(main, ol);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div7, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div8, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li4, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div9, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div10, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div11, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, t29);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li5, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div12, t30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div13, t32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, t33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div14, t34);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, t35);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li6, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div15, t36);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t37);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div16, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, t38);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div17, t39);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, t40);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li7, div18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div18, t41);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, t42);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(ol, li8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, div19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div19, t43);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, t44);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, div20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div20, t45);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, t46);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(li8, div21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append"])(div21, t47);
		},

		p: function update(changed, ctx) {
			if (changed.minutes) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t12, ctx.minutes);
			}

			if ((changed.seconds) && t14_value !== (t14_value = ctx.seconds > 9 ? ctx.seconds : '0' + ctx.seconds)) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data"])(t14, t14_value);
			}
		},

		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],

		d: function destroy(detaching) {
			if (detaching) {
				Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach"])(main);
			}
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	
  let seconds = 10;
  let minutes = 12;

  Object(svelte__WEBPACK_IMPORTED_MODULE_1__["onMount"])(() => {
    const interval = setInterval(() => {
      console.log("hi");
      if (seconds === 0) {
        $$invalidate('seconds', seconds = 60);
        $$invalidate('minutes', minutes -= 1);
      } else {
        $$invalidate('seconds', seconds -= 1);
      }
    }, 1000);

    return () => clearInterval(interval);
  });

	return { seconds, minutes };
}

class Routes extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-1u760zj-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], []);
	}
}

/* harmony default export */ __webpack_exports__["default"] = (Routes);

/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2luZGV4LnN2ZWx0ZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29KQTBKa0MsT0FBTyxHQUFHLENBQUMsT0FBRyxPQUFPLEdBQUcsR0FBRyxPQUFHLE9BQU87Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzBFQUEvQyxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs0RkFBUCxPQUFPOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhFQUFQLE9BQU87OzsyREFBRyxPQUFPLEdBQUcsQ0FBQyxPQUFHLE9BQU8sR0FBRyxHQUFHLE9BQUcsT0FBTzs7Ozs7Ozs7Ozs7Ozs7Ozs7Q0F4Slo7RUFDekQsSUFBSSxPQUFPLEdBQUcsRUFBRSxDQUFDO0VBQ2pCLElBQUksT0FBTyxHQUFHLEVBQUUsQ0FBQzs7RUFFakIsc0RBQU8sQ0FBQyxNQUFNO0lBQ1osTUFBTSxRQUFRLEdBQUcsV0FBVyxDQUFDLE1BQU07TUFDakMsT0FBTyxDQUFDLEdBQUcsQ0FBQyxJQUFJLENBQUMsQ0FBQztNQUNsQixJQUFJLE9BQU8sS0FBSyxDQUFDLEVBQUU7Z0NBQ2pCLE9BQU8sR0FBRyxHQUFFLENBQUM7Z0NBQ2IsT0FBTyxJQUFJLEVBQUMsQ0FBQztPQUNkLE1BQU07Z0NBQ0wsT0FBTyxJQUFJLEVBQUMsQ0FBQztPQUNkO0tBQ0YsRUFBRSxJQUFJLENBQUMsQ0FBQzs7SUFFVCxPQUFPLE1BQU0sYUFBYSxDQUFDLFFBQVEsQ0FBQyxDQUFDO0dBQ3RDLENBQUMsQ0FBQyIsImZpbGUiOiI0ZDZlODMxZWM1MjRhM2RhYmMxMy9pbmRleC5pbmRleC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGltcG9ydCB7IG9uTW91bnQgfSBmcm9tIFwic3ZlbHRlXCI7XG4gIGltcG9ydCBQbGF5QnV0dG9uIGZyb20gXCIuLi9jb21wb25lbnRzL1BsYXlCdXR0b24uc3ZlbHRlXCI7XG4gIGxldCBzZWNvbmRzID0gMTA7XG4gIGxldCBtaW51dGVzID0gMTI7XG5cbiAgb25Nb3VudCgoKSA9PiB7XG4gICAgY29uc3QgaW50ZXJ2YWwgPSBzZXRJbnRlcnZhbCgoKSA9PiB7XG4gICAgICBjb25zb2xlLmxvZyhcImhpXCIpO1xuICAgICAgaWYgKHNlY29uZHMgPT09IDApIHtcbiAgICAgICAgc2Vjb25kcyA9IDYwO1xuICAgICAgICBtaW51dGVzIC09IDE7XG4gICAgICB9IGVsc2Uge1xuICAgICAgICBzZWNvbmRzIC09IDE7XG4gICAgICB9XG4gICAgfSwgMTAwMCk7XG5cbiAgICByZXR1cm4gKCkgPT4gY2xlYXJJbnRlcnZhbChpbnRlcnZhbCk7XG4gIH0pO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgOmdsb2JhbCgqKSB7XG4gICAgbWFyZ2luOiAwO1xuICAgIHBhZGRpbmc6IDA7XG4gICAgZm9udC1mYW1pbHk6IFwiT3N3YWxkXCI7XG4gIH1cblxuICAuc2lkZS1pbmZvIHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7XG4gICAgbGVmdDogMDtcbiAgICBib3R0b206IDA7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xuICAgIGp1c3RpZnktY29udGVudDogZmxleC1lbmQ7XG4gICAgZ3JpZC1hcmVhOiBzaWRlaW5mbztcbiAgICB0cmFuc2Zvcm06IHJvdGF0ZSgyNzBkZWcpIHRyYW5zbGF0ZVkoNTV2aCk7XG4gICAgdHJhbnNmb3JtLW9yaWdpbjogbGVmdCBib3R0b207XG4gICAgZm9udC13ZWlnaHQ6IGJvbGQ7XG4gICAgbGluZS1oZWlnaHQ6IDE7XG4gICAgcGFkZGluZy1sZWZ0OiA0dmg7XG4gIH1cblxuICAubWF0Y2hlcyB7XG4gICAgcG9zaXRpb246IGZpeGVkO1xuICAgIHJpZ2h0OiAwO1xuICAgIHRvcDogMjB2aDtcbiAgICBsaXN0LXN0eWxlOiBub25lO1xuICAgIHdpZHRoOiA0MHZ3O1xuICAgIGZvbnQtc2l6ZTogOHZoO1xuICAgIHBhZGRpbmc6IDJyZW07XG4gIH1cblxuICAubWF0Y2hlcyA+IGxpOmZpcnN0LW9mLXR5cGUge1xuICAgIGJvcmRlci10b3A6IDFweCBzb2xpZCAjMTExO1xuICB9XG5cbiAgLm1hdGNoZXMgPiBsaSB7XG4gICAgZGlzcGxheTogZ3JpZDtcbiAgICBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDNlbSAxZnIgM2VtO1xuICAgIHdpZHRoOiAxMDAlO1xuICAgIGp1c3RpZnktY29udGVudDogc3BhY2UtYmV0d2VlbjtcbiAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgIzExMTtcbiAgfVxuICAucmVkID4gaW1nLFxuICAuYmx1ZSA+IGltZyB7XG4gICAgaGVpZ2h0OiA4dmg7XG4gICAgbWFyZ2luOiAwIDN2aDtcbiAgfVxuXG4gIC5yZWQge1xuICAgIHRleHQtYWxpZ246IGVuZDtcbiAgfVxuXG4gIC5WUyB7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICB9XG5cbiAgLnRpbWUge1xuICAgIGZvbnQtc2l6ZTogMzV2aDtcbiAgICBsaW5lLWhlaWdodDogMS4yO1xuICB9XG5cbiAgLnNlYXNvbiB7XG4gICAgZm9udC1zaXplOiA4dmg7XG4gICAgdHJhbnNmb3JtOiBzY2FsZVgoMi4zKTtcbiAgICB0cmFuc2Zvcm0tb3JpZ2luOiBsZWZ0O1xuICB9XG4gIC53ZWVrIHtcbiAgICBmb250LXNpemU6IDR2aDtcbiAgICBmb250LXdlaWdodDogaW5pdGlhbDtcbiAgfVxuXG4gIG1haW4ge1xuICAgIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG4gICAgcGFkZGluZzogMXJlbTtcbiAgICBjb2xvcjogIzExMTtcbiAgICBiYWNrZ3JvdW5kOiBsaW5lYXItZ3JhZGllbnQodG8gdG9wIHJpZ2h0LCAjNDI2MmFiLCAjMTlkOWJiIDUwJSk7XG4gICAgaGVpZ2h0OiAxMDB2aDtcbiAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlO1xuICB9XG5cbiAgLnBhcnRuZXJzIHtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXg6IDE7XG4gIH1cblxuICAucGFydG5lcnMgPiAqLFxuICAubXVzaWMgPiAqIHtcbiAgICBwYWRkaW5nOiAxcmVtIDFyZW07XG4gIH1cblxuICAudG9wIHtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICB9XG5cbiAgLm11c2ljIHtcbiAgICB3aGl0ZS1zcGFjZTogbm93cmFwO1xuICAgIG92ZXJmbG93LXg6IGhpZGRlbjtcbiAgfVxuXG4gIC5wYXJ0bmVycyA+IDpmaXJzdC1jaGlsZCB7XG4gICAgYm9yZGVyLXJpZ2h0OiAycHggc29saWQgIzIyMjtcbiAgfVxuXG4gIC5wYXJ0bmVycyB1bCB7XG4gICAgbGlzdC1zdHlsZTogbm9uZTtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIGZsZXg6IDE7XG4gICAgZ3JpZC1nYXA6IDNyZW07XG4gIH1cblxuICAubXVzaWMge1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDtcbiAgfVxuPC9zdHlsZT5cblxuPG1haW4+XG4gIDxkaXYgY2xhc3M9XCJ0b3BcIj5cbiAgICA8ZGl2IGNsYXNzPVwicGFydG5lcnNcIj5cbiAgICAgIDxoMj5PZmZpY2lhbCBQYXJ0bmVyczwvaDI+XG4gICAgICA8dWw+XG4gICAgICAgIDxsaT5Gb290TG9ja2VyPC9saT5cbiAgICAgICAgPGxpPlNoZWxsPC9saT5cbiAgICAgICAgPGxpPkxvZ2l0ZWNoPC9saT5cbiAgICAgICAgPGxpPkRYUmFjZXI8L2xpPlxuICAgICAgPC91bD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwibXVzaWNcIj5cbiAgICAgIDxwPlBlbnRha2lsbCAtIFRlYXIgb2YgdGhlIEdvZGRlc3M8L3A+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwic2lkZS1pbmZvXCI+XG4gICAgPGRpdiBjbGFzcz1cInRpbWVcIj4ge21pbnV0ZXN9OntzZWNvbmRzID4gOSA/IHNlY29uZHMgOiAnMCcgKyBzZWNvbmRzfSA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwic2Vhc29uXCI+U3VtbWVyIDE5PC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cIndlZWtcIj53ZWVrIG9uZTwvZGl2PlxuICA8L2Rpdj5cbiAgPG9sIGNsYXNzPVwibWF0Y2hlc1wiPlxuICAgIDxsaT5cbiAgICAgIDxkaXYgY2xhc3M9XCJibHVlXCI+RzI8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJWU1wiPlZTPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwicmVkXCI+U1BZPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPk9HPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwiVlNcIj5WUzwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cInJlZFwiPlZJVDwvZGl2PlxuICAgIDwvbGk+XG4gICAgPGxpPlxuICAgICAgPGRpdiBjbGFzcz1cImJsdWVcIj5SR0U8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJWU1wiPlZTPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwicmVkXCI+TVNGPC9kaXY+XG4gICAgPC9saT5cbiAgICA8bGk+XG4gICAgICA8ZGl2IGNsYXNzPVwiYmx1ZVwiPlxuICAgICAgICA8aW1nIHNyYz1cIi9mbmMucG5nXCIgLz5cbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cIlZTXCI+VlM8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyZWRcIj5TSzwvZGl2PlxuICAgIDwvbGk+XG4gICAgPGxpPlxuICAgICAgPGRpdiBjbGFzcz1cImJsdWVcIj5TMDQ8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJWU1wiPlZTPC9kaXY+XG4gICAgICA8ZGl2IGNsYXNzPVwicmVkXCI+WEw8L2Rpdj5cbiAgICA8L2xpPlxuICA8L29sPlxuPC9tYWluPlxuIl0sInNvdXJjZVJvb3QiOiIifQ==